# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit]
exclude: '^(\.git.*|\.vscode.*\.json|.*\.code-workspace|venv.*|build.*|test.*|out.*)'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.5
    hooks:
    -   id: clang-format
-   repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.3
    hooks:
    -   id: cmakelint
